### ISSUE TITLE
Compilation Issues

### ISSUE THREAD

**Issue by zouabimourad** [dizzib/WhoDoTheyServe.com#3]
Hi,

I tried to compile the project from the code source.  After some efforts i succeeded to start the server but two files are missing lib.js and app.js

Any Idea ? ( I'm not a nodejs Guy ) 
![compile_issues]
(https://cloud.githubusercontent.com/assets/1597453/3950768/6258fafe-26cb-11e4-8c69-9478cc7c7d94.png)

**Comment by johnp2015** [comment]
On Ubuntu I cannot compile:

connecting to firefox marionette at localhost
    √ openauth oa1 leg1
    ? openauth oa1 leg2 :
    1) openauth oa1 leg2

  db-cache


  51 passing (2s)
  2 pending
  1 failing




  1) api openauth oa1 leg2 :

      + expected - actual

      +"http://undefined:4001/#/user"
      -"http://SITE_DOMAIN_NAME:4001/#/user"






30 Jan 14:57:11 - Exited with code 1

    1) "before all" hook

  0 passing (12s)
  1 failing




  1) app "before all" hook:
     Uncaught TypeError: Cannot call method 'on' of undefined
      at Object.CommandStream (/home/johnp/WhoDoTheyServe.com/_build/dev/node_modules/marionette-client/lib/marionette/command-stream.js:23:12)
      at Object.<anonymous> (/home/johnp/WhoDoTheyServe.com/_build/dev/node_modules/marionette-client/lib/marionette/drivers/tcp.js:71:28)
      at waitForSocket (/home/johnp/WhoDoTheyServe.com/_build/dev/node_modules/marionette-client/node_modules/socket-retry-connect/index.js:37:12)
      at timer._onTimeout (timers.js:219:16)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)



30 Jan 14:57:22 - Exited with code 1

**Comment by dizzib** [comment]
Fixed on dev branch

**Comment by johnp2015** [comment]
Got a lot further on ubuntu with Dev build but still failing. 

  db-cache
    ? collection cache:
    √ collection cache (57ms)
    ? query-by-entity cache:
    √ query-by-entity cache


  289 passing (5s)
  30 pending

2 Feb 10:47:21 - Unit & api tests passed in 6.835s

    1) "before all" hook

  0 passing (12s)
  1 failing



  1) app "before all" hook:
     Uncaught TypeError: Cannot call method 'on' of undefined
      at Object.CommandStream (/home/johnp/WhoDoTheyServe.com/_build/dev/node_modules/marionette-client/lib/marionette/command-stream.js:23:12)
      at Object.<anonymous> (/home/johnp/WhoDoTheyServe.com/_build/dev/node_modules/marionette-client/lib/marionette/drivers/tcp.js:71:28)
      at waitForSocket (/home/johnp/WhoDoTheyServe.com/_build/dev/node_modules/marionette-client/node_modules/socket-retry-connect/index.js:37:12)
      at timer._onTimeout (timers.js:219:16)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)




2 Feb 10:47:29 - Exited with code 1

**Comment by dizzib** [comment]
Yes, the app (integration) tests need a running instance of Firefox (with Marionette which only the later version have) so try starting an instance before retrying. Or you can always disable the app tests entirely by entering `b.t2` in the task runner.

**Comment by johnp2015** [comment]
Working now locally, thanks bunch.

Final question, is there anyway to create new maps and locally become an admin, I cannot seem to login??

**Comment by dizzib** [comment]
Great! The first user added via http://localhost:4000/#/user/signup will be the admin who can then add normal users via the same url.
